export type BlogSection = { title: string; paragraphs: string[]; bullets?: string[] };
export type BlogPost = { slug:string; title:string; description:string; eyebrow:string; date:string; readTime:string; image:string; imageAlt:string; keywords:string[]; intro:string; sections:BlogSection[]; external?:{label:string;href:string} };

export const posts: BlogPost[] = [
  {slug:"laver-bonnet-haoussa-dakar",title:"Comment laver un bonnet haoussa à Dakar sans l’abîmer",description:"Méthode douce pour nettoyer, sécher et conserver la forme d’un bonnet haoussa à Dakar malgré la chaleur, la poussière et l’humidité.",eyebrow:"Entretien du bonnet haoussa",date:"30 août 2026",readTime:"5 min",image:"/assets/lavage-bonnet-haoussa-dakar.png",imageAlt:"Service de lavage de bonnets haoussa à Dieuppeul, Keur Baye Niass, Dakar",keywords:["lavage bonnet haoussa Dakar","entretenir bonnet haoussa","nettoyer bonnet africain","bonnet haoussa Dakar"],intro:"Un bonnet haoussa possède souvent une structure précise et des broderies qui méritent un entretien délicat. À Dakar, la transpiration, la poussière et l’air marin peuvent marquer le tissu : un nettoyage doux aide à préserver les couleurs et la tenue du bonnet.",sections:[
    {title:"Avant le lavage : identifier la matière",paragraphs:["Commencez toujours par vérifier l’étiquette ou demander au vendeur la composition du bonnet. La laine, le coton et les fibres mélangées ne réagissent pas de la même manière. En cas de doute, privilégiez un nettoyage localisé et testez l’eau sur une zone peu visible."],bullets:["Retirez la poussière avec une brosse très souple.","Testez la tenue des couleurs avec un linge blanc humide.","Évitez l’eau de Javel, les détachants agressifs et l’eau chaude."]},
    {title:"La méthode douce recommandée",paragraphs:["Remplissez une bassine d’eau fraîche ou légèrement tiède et ajoutez une petite quantité de savon doux. Nettoyez le bonnet à la main sans le tordre, en insistant délicatement sur le bandeau intérieur. Un rinçage rapide limite la déformation et la migration des couleurs.","Pour une petite tache, tamponnez au lieu de frotter. Cette précaution protège les fils décoratifs et les broderies du bonnet haoussa."],bullets:["Lavage court à la main.","Pression légère avec une serviette pour retirer l’excès d’eau.","Aucun essorage mécanique."]},
    {title:"Bien sécher son bonnet sous le climat de Dakar",paragraphs:["Redonnez immédiatement sa forme au bonnet, puis laissez-le sécher à plat dans un endroit ventilé. Le soleil direct de Dakar peut ternir certaines couleurs ; choisissez donc l’ombre et évitez le sèche-linge. Rangez ensuite le bonnet au sec, sans poser d’objet lourd dessus.","Vous pouvez découvrir nos modèles et demander un conseil adapté à votre matière dans la collection de bonnets haoussa à Dakar."]}
  ],external:{label:"Consulter les conseils d’entretien textile de Woolmark",href:"https://www.woolmark.com/care/"}},
  {slug:"mesurer-taille-bonnet",title:"Comment prendre ses mesures pour choisir la taille de son bonnet",description:"Mesurez correctement votre tour de tête et choisissez entre les tailles 56, 57, 58, 59 et 60 pour commander un bonnet à Dakar.",eyebrow:"Guide des tailles",date:"30 août 2026",readTime:"4 min",image:"/assets/comment-mesurer-taille-bonnet.png",imageAlt:"Homme mesurant son tour de tête avec un mètre ruban et schéma de prise de mesure pour choisir la taille d’un bonnet",keywords:["mesure taille bonnet","tour de tête bonnet","taille bonnet Dakar","bonnet taille 56 58 60"],intro:"Une bonne mesure évite un bonnet trop serré, qui laisse une marque sur le front, ou trop large, qui bouge pendant la journée. Il suffit d’un mètre ruban souple et de moins d’une minute pour trouver votre taille.",sections:[
    {title:"Mesurer le tour de tête en trois étapes",paragraphs:["Placez le mètre ruban au milieu du front, légèrement au-dessus des sourcils. Faites-le passer au-dessus des oreilles puis autour de la partie la plus large de l’arrière du crâne. Gardez le ruban horizontal, ajusté mais sans le serrer."],bullets:["Mesurez deux fois pour confirmer le résultat.","Notez la valeur en centimètres.","Si vous utilisez une ficelle, mesurez ensuite sa longueur avec une règle."]},
    {title:"Transformer la mesure en taille de bonnet",paragraphs:["Chez FuyoDati, les tailles 56 à 60 correspondent au tour de tête en centimètres. Une mesure de 58 cm indique donc généralement une taille 58. Si votre résultat se situe entre deux tailles, choisissez la taille supérieure pour plus de confort."],bullets:["55,5 à 56 cm : taille 56.","56,5 à 57 cm : taille 57.","57,5 à 58 cm : taille 58.","58,5 à 59 cm : taille 59.","59,5 à 60 cm : taille 60."]},
    {title:"Tenir compte de la forme et de la coiffure",paragraphs:["La coupe d’un bonnet togolais, carré ou haoussa peut influencer la sensation de maintien. Mesurez votre tête avec la coiffure que vous porterez le jour de la cérémonie. En cas d’hésitation, envoyez votre mesure sur WhatsApp avant de commander votre bonnet à Dakar."]}
  ],external:{label:"Voir le guide officiel de prise de mesure New Era",href:"https://www.neweracap.com/pages/sizing-chart"}},
  {slug:"choisir-bonnet-ceremonie-dakar",title:"Quel bonnet choisir pour une cérémonie à Dakar ?",description:"Guide pour choisir un bonnet togolais, carré ou haoussa à Dakar selon votre tenue, l’occasion, la couleur et votre style.",eyebrow:"Style et cérémonie",date:"30 août 2026",readTime:"6 min",image:"/assets/bonnet-mariage-ceremonie-dakar.png",imageAlt:"Homme souriant en grand boubou blanc portant un bonnet haoussa pour un mariage à Dakar",keywords:["bonnet cérémonie Dakar","bonnet mariage Dakar","bonnet baptême Dakar","choisir bonnet haoussa"],intro:"Mariage, baptême, Korité, Tabaski, Gamou ou réception : le bonnet termine la silhouette et peut faire le lien entre le boubou, les chaussures et les accessoires. Le bon choix dépend d’abord du niveau de formalité et de l’équilibre des couleurs.",sections:[
    {title:"Bonnet togolais : une élégance facile à associer",paragraphs:["Le bonnet togolais convient aussi bien à une cérémonie qu’à une tenue habillée du quotidien. Un modèle noir, gris ou bleu nuit accompagne facilement un grand boubou riche en détails. Les tons or, ivoire ou jaune apportent davantage de lumière aux photos et aux célébrations."]},
    {title:"Bonnet haoussa : pour une présence plus graphique",paragraphs:["Le bonnet haoussa se distingue par ses motifs, ses contrastes et ses broderies. Il fonctionne particulièrement bien avec une tenue unie ou composée de deux couleurs principales. Pour éviter de surcharger l’ensemble, reprenez une couleur du bonnet dans le boubou ou les chaussures."],bullets:["Tenue très brodée : bonnet sobre ou ton sur ton.","Tenue unie : bonnet haoussa graphique ou couleur contrastante.","Cérémonie en journée : ivoire, sable, bleu ou vert lumineux.","Soirée : noir, bordeaux, bleu nuit ou doré."]},
    {title:"Bonnet carré : une silhouette nette et contemporaine",paragraphs:["Le bonnet carré crée une ligne structurée qui s’accorde bien avec les coupes modernes. Noir pour la polyvalence, blanc ivoire pour les célébrations, bleu royal pour affirmer la couleur ou bordeaux pour une allure profonde : choisissez en fonction du tissu dominant de votre tenue."]},
    {title:"Les trois vérifications avant de commander à Dakar",paragraphs:["Vérifiez votre tour de tête, observez la couleur de votre tenue à la lumière du jour et confirmez la disponibilité du modèle. FuyoDati propose un conseil sur WhatsApp et une livraison à Dakar sous 24 à 48 heures après confirmation."]}
  ]}
];
export const getPost=(slug:string)=>posts.find((post)=>post.slug===slug);
